### ISSUE TITLE
Requires RMP, but no instructions on how to use it or make it work

### ISSUE THREAD

**Issue by cglewis** [realm/github-gantt#9]
```
        let adminUser = Realm.Sync.User.adminUser(config.RMP_ADMIN_TOKEN);
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by snauth** [comment]
This means that you have to enable strict mode when starting the program:
`node --use_strict index.js`
